using System.Text.Json.Serialization;

namespace Sonari.Sonarr.Models;

public record Series(
    [property: JsonPropertyName("title")]
    string Title,
    [property: JsonPropertyName("alternateTitles")]
    IReadOnlyList<AlternateTitle> AlternateTitles,
    [property: JsonPropertyName("sortTitle")]
    string SortTitle,
    [property: JsonPropertyName("seasonCount")]
    int SeasonCount,
    [property: JsonPropertyName("totalEpisodeCount")]
    int TotalEpisodeCount,
    [property: JsonPropertyName("episodeCount")]
    int EpisodeCount,
    [property: JsonPropertyName("episodeFileCount")]
    int EpisodeFileCount,
    [property: JsonPropertyName("sizeOnDisk")]
    object SizeOnDisk,
    [property: JsonPropertyName("status")]
    string Status,
    [property: JsonPropertyName("overview")]
    string Overview,
    [property: JsonPropertyName("previousAiring")]
    DateTime PreviousAiring,
    [property: JsonPropertyName("network")]
    string Network,
    [property: JsonPropertyName("airTime")]
    string AirTime,
    [property: JsonPropertyName("images")]
    IReadOnlyList<Image> Images,
    [property: JsonPropertyName("seasons")]
    IReadOnlyList<Season> Seasons,
    [property: JsonPropertyName("year")]
    int Year,
    [property: JsonPropertyName("path")]
    string Path,
    [property: JsonPropertyName("profileId")]
    int ProfileId,
    [property: JsonPropertyName("languageProfileId")]
    int LanguageProfileId,
    [property: JsonPropertyName("seasonFolder")]
    bool SeasonFolder,
    [property: JsonPropertyName("monitored")]
    bool Monitored,
    [property: JsonPropertyName("useSceneNumbering")]
    bool UseSceneNumbering,
    [property: JsonPropertyName("runtime")]
    int Runtime,
    [property: JsonPropertyName("tvdbId")]
    int TvdbId,
    [property: JsonPropertyName("tvRageId")]
    int TvRageId,
    [property: JsonPropertyName("tvMazeId")]
    int TvMazeId,
    [property: JsonPropertyName("firstAired")]
    DateTime FirstAired,
    [property: JsonPropertyName("lastInfoSync")]
    DateTime LastInfoSync,
    [property: JsonPropertyName("seriesType")]
    string SeriesType,
    [property: JsonPropertyName("cleanTitle")]
    string CleanTitle,
    [property: JsonPropertyName("imdbId")]
    string ImdbId,
    [property: JsonPropertyName("titleSlug")]
    string TitleSlug,
    [property: JsonPropertyName("certification")]
    string Certification,
    [property: JsonPropertyName("genres")]
    IReadOnlyList<string> Genres,
    [property: JsonPropertyName("tags")]
    IReadOnlyList<int> Tags,
    [property: JsonPropertyName("added")]
    DateTime Added,
    [property: JsonPropertyName("ratings")]
    Ratings Ratings,
    [property: JsonPropertyName("qualityProfileId")]
    int QualityProfileId,
    [property: JsonPropertyName("id")]
    int Id,
    [property: JsonPropertyName("nextAiring")]
    DateTime? NextAiring
);